Tried to make more robust in case paths vary

diff --git a/get_list_of_modules b/get_list_of_modules
--- a/get_list_of_modules
+++ b/get_list_of_modules
@@ -1,12 +1,20 @@
 #!/bin/bash
 
-type module 2>/dev/null
+type module 1>/dev/null 2>/dev/null
 if [ $? -ne 0 ]
 then
-	function module () 
-	{ 
-		eval `/usr/bin/modulecmd bash $*`
-	}
+	modulecmd_exe=$(which modulecmd)
+	if [ $? -ne 0 ]
+	then
+		echo "Error: Neither Lmod nor Environment Modules could be detected."
+		echo "Exiting."
+		exit 1
+	else
+		function module () 
+		{ 
+			eval `"${modulecmd_exe}" bash $*`
+		}
+	fi
 fi
 
 home_dir=$(eval echo ~)
